"""
意象-情绪映射词典（完整版 300+ 词条）

字段说明：
- valence_adj: 对情感效价的修正值
- arousal: 该意象的固有唤醒度
- effect: 触发的视觉粒子效果名称
- color: 代表色（hex）
- instrument: 适合的乐器音色
"""

IMAGERY_DICT = {

    # ==================== 天气与气象（40+）====================
    "雨":       {"valence_adj": -0.10, "arousal": 0.40, "effect": "rain",       "color": "#4A90D9", "instrument": "piano"},
    "大雨":     {"valence_adj": -0.15, "arousal": 0.70, "effect": "heavy_rain", "color": "#2C3E73", "instrument": "piano"},
    "小雨":     {"valence_adj": -0.05, "arousal": 0.20, "effect": "light_rain", "color": "#7EB6D9", "instrument": "piano"},
    "细雨":     {"valence_adj": -0.03, "arousal": 0.15, "effect": "light_rain", "color": "#8EC4E8", "instrument": "piano"},
    "暴雨":     {"valence_adj": -0.20, "arousal": 0.90, "effect": "storm",      "color": "#1A1A3E", "instrument": "strings"},
    "雷阵雨":   {"valence_adj": -0.18, "arousal": 0.85, "effect": "storm",      "color": "#2A2A50", "instrument": "strings"},
    "梅雨":     {"valence_adj": -0.08, "arousal": 0.25, "effect": "rain",       "color": "#6699AA", "instrument": "piano"},
    "淋雨":     {"valence_adj": -0.15, "arousal": 0.50, "effect": "heavy_rain", "color": "#3A5A8C", "instrument": "piano"},
    "雨滴":     {"valence_adj": -0.03, "arousal": 0.20, "effect": "light_rain", "color": "#7CAAD4", "instrument": "celesta"},
    "雪":       {"valence_adj":  0.05, "arousal": 0.15, "effect": "snow",       "color": "#E8E8F0", "instrument": "celesta"},
    "大雪":     {"valence_adj":  0.00, "arousal": 0.30, "effect": "heavy_snow", "color": "#C8C8E0", "instrument": "celesta"},
    "小雪":     {"valence_adj":  0.08, "arousal": 0.10, "effect": "snow",       "color": "#F0F0F8", "instrument": "celesta"},
    "飘雪":     {"valence_adj":  0.05, "arousal": 0.12, "effect": "snow",       "color": "#E0E0F0", "instrument": "celesta"},
    "暴风雪":   {"valence_adj": -0.15, "arousal": 0.85, "effect": "storm",      "color": "#9090B0", "instrument": "strings"},
    "雪花":     {"valence_adj":  0.10, "arousal": 0.10, "effect": "snow",       "color": "#F5F5FF", "instrument": "celesta"},
    "风":       {"valence_adj": -0.05, "arousal": 0.50, "effect": "wind",       "color": "#A8C8C8", "instrument": "flute"},
    "微风":     {"valence_adj":  0.10, "arousal": 0.20, "effect": "breeze",     "color": "#C8E8D8", "instrument": "flute"},
    "清风":     {"valence_adj":  0.12, "arousal": 0.20, "effect": "breeze",     "color": "#B8E0C8", "instrument": "flute"},
    "暴风":     {"valence_adj": -0.20, "arousal": 0.90, "effect": "storm",      "color": "#3D3D5C", "instrument": "strings"},
    "狂风":     {"valence_adj": -0.18, "arousal": 0.85, "effect": "storm",      "color": "#4A4A6A", "instrument": "strings"},
    "寒风":     {"valence_adj": -0.15, "arousal": 0.60, "effect": "wind",       "color": "#8090A8", "instrument": "strings"},
    "秋风":     {"valence_adj": -0.05, "arousal": 0.30, "effect": "leaves",     "color": "#C8A848", "instrument": "guitar"},
    "春风":     {"valence_adj":  0.15, "arousal": 0.30, "effect": "breeze",     "color": "#A8D8A8", "instrument": "flute"},
    "雷":       {"valence_adj": -0.15, "arousal": 0.95, "effect": "lightning",  "color": "#FFFF66", "instrument": "drums"},
    "雷声":     {"valence_adj": -0.12, "arousal": 0.90, "effect": "lightning",  "color": "#FFFF88", "instrument": "drums"},
    "闪电":     {"valence_adj": -0.10, "arousal": 0.95, "effect": "lightning",  "color": "#FFFF99", "instrument": "drums"},
    "阳光":     {"valence_adj":  0.20, "arousal": 0.50, "effect": "sunlight",  "color": "#FFD700", "instrument": "guitar"},
    "晴":       {"valence_adj":  0.15, "arousal": 0.40, "effect": "sunlight",  "color": "#FFE44D", "instrument": "guitar"},
    "晴天":     {"valence_adj":  0.15, "arousal": 0.40, "effect": "sunlight",  "color": "#FFE44D", "instrument": "guitar"},
    "晴朗":     {"valence_adj":  0.18, "arousal": 0.45, "effect": "sunlight",  "color": "#FFDA33", "instrument": "guitar"},
    "云":       {"valence_adj":  0.00, "arousal": 0.20, "effect": "clouds",    "color": "#D3D3E8", "instrument": "synth_pad"},
    "白云":     {"valence_adj":  0.10, "arousal": 0.15, "effect": "clouds",    "color": "#E8E8F8", "instrument": "synth_pad"},
    "乌云":     {"valence_adj": -0.15, "arousal": 0.50, "effect": "clouds",    "color": "#4A4A6A", "instrument": "strings"},
    "云层":     {"valence_adj":  0.00, "arousal": 0.20, "effect": "clouds",    "color": "#B8B8D0", "instrument": "synth_pad"},
    "雾":       {"valence_adj": -0.05, "arousal": 0.15, "effect": "fog",       "color": "#B8B8C8", "instrument": "synth_pad"},
    "浓雾":     {"valence_adj": -0.10, "arousal": 0.20, "effect": "fog",       "color": "#909098", "instrument": "synth_pad"},
    "薄雾":     {"valence_adj":  0.00, "arousal": 0.10, "effect": "fog",       "color": "#D0D0D8", "instrument": "synth_pad"},
    "晨雾":     {"valence_adj":  0.05, "arousal": 0.12, "effect": "fog",       "color": "#C8C8D8", "instrument": "flute"},
    "彩虹":     {"valence_adj":  0.30, "arousal": 0.60, "effect": "rainbow",   "color": "#FF69B4", "instrument": "bells"},
    "霞":       {"valence_adj":  0.15, "arousal": 0.30, "effect": "glow",      "color": "#FF7F50", "instrument": "strings"},
    "晚霞":     {"valence_adj":  0.10, "arousal": 0.30, "effect": "sunset",    "color": "#FF6347", "instrument": "strings"},
    "朝霞":     {"valence_adj":  0.20, "arousal": 0.40, "effect": "sunrise",   "color": "#FF8C00", "instrument": "flute"},
    "霜":       {"valence_adj": -0.08, "arousal": 0.15, "effect": "snow",      "color": "#D8D8E8", "instrument": "celesta"},
    "露":       {"valence_adj":  0.08, "arousal": 0.10, "effect": "sparkle",   "color": "#C8E8E8", "instrument": "celesta"},
    "露珠":     {"valence_adj":  0.10, "arousal": 0.10, "effect": "sparkle",   "color": "#B8E0E0", "instrument": "celesta"},
    "冰":       {"valence_adj": -0.10, "arousal": 0.20, "effect": "sparkle",   "color": "#A8D8F0", "instrument": "celesta"},
    "冰雪":     {"valence_adj": -0.05, "arousal": 0.25, "effect": "snow",      "color": "#C0D8F0", "instrument": "celesta"},

    # ==================== 天体与宇宙（25+）====================
    "太阳":     {"valence_adj":  0.20, "arousal": 0.50, "effect": "sunlight",  "color": "#FFA500", "instrument": "guitar"},
    "日出":     {"valence_adj":  0.25, "arousal": 0.50, "effect": "sunrise",   "color": "#FF4500", "instrument": "strings"},
    "日落":     {"valence_adj":  0.05, "arousal": 0.30, "effect": "sunset",    "color": "#FF6347", "instrument": "strings"},
    "夕阳":     {"valence_adj":  0.05, "arousal": 0.30, "effect": "sunset",    "color": "#FF5733", "instrument": "strings"},
    "落日":     {"valence_adj":  0.03, "arousal": 0.28, "effect": "sunset",    "color": "#E8532A", "instrument": "strings"},
    "月":       {"valence_adj":  0.00, "arousal": 0.15, "effect": "moonlight", "color": "#FFFACD", "instrument": "piano"},
    "月亮":     {"valence_adj":  0.00, "arousal": 0.15, "effect": "moonlight", "color": "#FFFACD", "instrument": "piano"},
    "月光":     {"valence_adj":  0.05, "arousal": 0.10, "effect": "moonlight", "color": "#F0E68C", "instrument": "piano"},
    "明月":     {"valence_adj":  0.05, "arousal": 0.15, "effect": "moonlight", "color": "#FAFAC8", "instrument": "piano"},
    "弯月":     {"valence_adj":  0.03, "arousal": 0.12, "effect": "moonlight", "color": "#F0E8B0", "instrument": "piano"},
    "满月":     {"valence_adj":  0.08, "arousal": 0.18, "effect": "moonlight", "color": "#FFFFF0", "instrument": "piano"},
    "新月":     {"valence_adj": -0.02, "arousal": 0.10, "effect": "moonlight", "color": "#E8E0A8", "instrument": "piano"},
    "星":       {"valence_adj":  0.10, "arousal": 0.20, "effect": "stars",     "color": "#FFD700", "instrument": "celesta"},
    "星星":     {"valence_adj":  0.15, "arousal": 0.20, "effect": "stars",     "color": "#FFD700", "instrument": "celesta"},
    "星空":     {"valence_adj":  0.10, "arousal": 0.20, "effect": "stars",     "color": "#191970", "instrument": "synth_pad"},
    "星辰":     {"valence_adj":  0.10, "arousal": 0.22, "effect": "stars",     "color": "#2A2A6A", "instrument": "synth_pad"},
    "繁星":     {"valence_adj":  0.15, "arousal": 0.25, "effect": "stars",     "color": "#FFE066", "instrument": "celesta"},
    "流星":     {"valence_adj":  0.20, "arousal": 0.60, "effect": "shooting_star","color": "#FFD700","instrument": "celesta"},
    "银河":     {"valence_adj":  0.15, "arousal": 0.25, "effect": "stars",     "color": "#B8C8FF", "instrument": "synth_pad"},
    "宇宙":     {"valence_adj":  0.05, "arousal": 0.30, "effect": "stars",     "color": "#0B0B45", "instrument": "synth_pad"},
    "太空":     {"valence_adj":  0.05, "arousal": 0.30, "effect": "stars",     "color": "#0A0A3A", "instrument": "synth_pad"},
    "天空":     {"valence_adj":  0.10, "arousal": 0.30, "effect": "clouds",    "color": "#87CEEB", "instrument": "synth_pad"},
    "苍穹":     {"valence_adj":  0.05, "arousal": 0.28, "effect": "clouds",    "color": "#6A9EC8", "instrument": "synth_pad"},

    # ==================== 水域与海洋（20+）====================
    "水":       {"valence_adj":  0.05, "arousal": 0.30, "effect": "ripple",    "color": "#4682B4", "instrument": "piano"},
    "清水":     {"valence_adj":  0.10, "arousal": 0.20, "effect": "ripple",    "color": "#5CACEE", "instrument": "piano"},
    "河":       {"valence_adj":  0.05, "arousal": 0.35, "effect": "flow",      "color": "#5B9BD5", "instrument": "piano"},
    "河流":     {"valence_adj":  0.05, "arousal": 0.35, "effect": "flow",      "color": "#5B9BD5", "instrument": "piano"},
    "小河":     {"valence_adj":  0.10, "arousal": 0.25, "effect": "flow",      "color": "#6CB4E0", "instrument": "piano"},
    "溪":       {"valence_adj":  0.12, "arousal": 0.25, "effect": "flow",      "color": "#6CB4E0", "instrument": "celesta"},
    "溪流":     {"valence_adj":  0.12, "arousal": 0.25, "effect": "flow",      "color": "#6CB4E0", "instrument": "celesta"},
    "小溪":     {"valence_adj":  0.15, "arousal": 0.20, "effect": "flow",      "color": "#78C0E8", "instrument": "celesta"},
    "泉":       {"valence_adj":  0.12, "arousal": 0.20, "effect": "ripple",    "color": "#70B8D8", "instrument": "celesta"},
    "泉水":     {"valence_adj":  0.12, "arousal": 0.20, "effect": "ripple",    "color": "#70B8D8", "instrument": "celesta"},
    "瀑布":     {"valence_adj":  0.10, "arousal": 0.75, "effect": "heavy_rain","color": "#3A8CC0", "instrument": "strings"},
    "海":       {"valence_adj":  0.10, "arousal": 0.50, "effect": "wave",      "color": "#006994", "instrument": "synth_pad"},
    "大海":     {"valence_adj":  0.10, "arousal": 0.50, "effect": "wave",      "color": "#006994", "instrument": "synth_pad"},
    "海洋":     {"valence_adj":  0.10, "arousal": 0.50, "effect": "wave",      "color": "#005580", "instrument": "synth_pad"},
    "海浪":     {"valence_adj":  0.05, "arousal": 0.60, "effect": "wave",      "color": "#1E90FF", "instrument": "synth_pad"},
    "波浪":     {"valence_adj":  0.05, "arousal": 0.55, "effect": "wave",      "color": "#2898E8", "instrument": "synth_pad"},
    "潮汐":     {"valence_adj":  0.00, "arousal": 0.40, "effect": "wave",      "color": "#2070A0", "instrument": "synth_pad"},
    "湖":       {"valence_adj":  0.10, "arousal": 0.15, "effect": "ripple",    "color": "#5F9EA0", "instrument": "piano"},
    "湖泊":     {"valence_adj":  0.10, "arousal": 0.15, "effect": "ripple",    "color": "#5F9EA0", "instrument": "piano"},
    "湖面":     {"valence_adj":  0.08, "arousal": 0.12, "effect": "ripple",    "color": "#68A8A8", "instrument": "piano"},
    "池塘":     {"valence_adj":  0.08, "arousal": 0.10, "effect": "ripple",    "color": "#70A8A0", "instrument": "piano"},
    "深海":     {"valence_adj": -0.05, "arousal": 0.35, "effect": "wave",      "color": "#003060", "instrument": "synth_pad"},

    # ==================== 山岳与大地（20+）====================
    "山":       {"valence_adj":  0.05, "arousal": 0.30, "effect": "float",     "color": "#556B2F", "instrument": "strings"},
    "高山":     {"valence_adj":  0.05, "arousal": 0.40, "effect": "float",     "color": "#2F4F2F", "instrument": "strings"},
    "山峰":     {"valence_adj":  0.08, "arousal": 0.45, "effect": "float",     "color": "#3A5A3A", "instrument": "strings"},
    "群山":     {"valence_adj":  0.05, "arousal": 0.35, "effect": "float",     "color": "#4A6A4A", "instrument": "strings"},
    "远山":     {"valence_adj":  0.00, "arousal": 0.20, "effect": "fog",       "color": "#8899AA", "instrument": "synth_pad"},
    "山谷":     {"valence_adj":  0.05, "arousal": 0.20, "effect": "fog",       "color": "#5A7A5A", "instrument": "flute"},
    "峡谷":     {"valence_adj": -0.03, "arousal": 0.35, "effect": "wind",      "color": "#6A5A4A", "instrument": "strings"},
    "悬崖":     {"valence_adj": -0.10, "arousal": 0.65, "effect": "wind",      "color": "#5A4A3A", "instrument": "strings"},
    "大地":     {"valence_adj":  0.05, "arousal": 0.30, "effect": "float",     "color": "#8B7355", "instrument": "strings"},
    "田野":     {"valence_adj":  0.15, "arousal": 0.25, "effect": "breeze",    "color": "#90B860", "instrument": "guitar"},
    "平原":     {"valence_adj":  0.10, "arousal": 0.20, "effect": "breeze",    "color": "#A0C870", "instrument": "guitar"},
    "草原":     {"valence_adj":  0.15, "arousal": 0.30, "effect": "breeze",    "color": "#78B850", "instrument": "flute"},
    "旷野":     {"valence_adj": -0.05, "arousal": 0.30, "effect": "wind",      "color": "#A0A060", "instrument": "flute"},
    "荒野":     {"valence_adj": -0.10, "arousal": 0.35, "effect": "dust",      "color": "#B0A070", "instrument": "strings"},
    "沙漠":     {"valence_adj": -0.05, "arousal": 0.30, "effect": "dust",      "color": "#EDC9AF", "instrument": "flute"},
    "戈壁":     {"valence_adj": -0.10, "arousal": 0.30, "effect": "dust",      "color": "#C8A878", "instrument": "flute"},
    "沙丘":     {"valence_adj": -0.03, "arousal": 0.25, "effect": "dust",      "color": "#D8B888", "instrument": "flute"},
    "泥土":     {"valence_adj":  0.00, "arousal": 0.15, "effect": "float",     "color": "#8B6914", "instrument": "guitar"},
    "石头":     {"valence_adj":  0.00, "arousal": 0.20, "effect": "float",     "color": "#808080", "instrument": "piano"},

    # ==================== 植物与花卉（35+）====================
    "花":       {"valence_adj":  0.20, "arousal": 0.35, "effect": "petals",    "color": "#FFB6C1", "instrument": "bells"},
    "鲜花":     {"valence_adj":  0.22, "arousal": 0.35, "effect": "petals",    "color": "#FF9EAF", "instrument": "bells"},
    "花朵":     {"valence_adj":  0.20, "arousal": 0.30, "effect": "petals",    "color": "#FFB6C1", "instrument": "bells"},
    "花瓣":     {"valence_adj":  0.18, "arousal": 0.25, "effect": "petals",    "color": "#FFAABB", "instrument": "bells"},
    "花香":     {"valence_adj":  0.22, "arousal": 0.30, "effect": "petals",    "color": "#FFD0E0", "instrument": "flute"},
    "樱花":     {"valence_adj":  0.25, "arousal": 0.30, "effect": "petals",    "color": "#FFB7C5", "instrument": "bells"},
    "桃花":     {"valence_adj":  0.22, "arousal": 0.30, "effect": "petals",    "color": "#FF8FAF", "instrument": "bells"},
    "梅花":     {"valence_adj":  0.15, "arousal": 0.25, "effect": "petals",    "color": "#FF6088", "instrument": "flute"},
    "荷花":     {"valence_adj":  0.15, "arousal": 0.20, "effect": "petals",    "color": "#F8C8DC", "instrument": "flute"},
    "莲花":     {"valence_adj":  0.18, "arousal": 0.18, "effect": "petals",    "color": "#F0C0D0", "instrument": "flute"},
    "玫瑰":     {"valence_adj":  0.20, "arousal": 0.40, "effect": "petals",    "color": "#FF1744", "instrument": "strings"},
    "菊花":     {"valence_adj":  0.05, "arousal": 0.20, "effect": "petals",    "color": "#FFD700", "instrument": "guitar"},
    "向日葵":   {"valence_adj":  0.25, "arousal": 0.45, "effect": "sunlight",  "color": "#FFD700", "instrument": "guitar"},
    "兰花":     {"valence_adj":  0.15, "arousal": 0.15, "effect": "float",     "color": "#DA70D6", "instrument": "flute"},
    "百合":     {"valence_adj":  0.18, "arousal": 0.20, "effect": "petals",    "color": "#FFFFFF", "instrument": "bells"},
    "牡丹":     {"valence_adj":  0.20, "arousal": 0.35, "effect": "petals",    "color": "#FF3366", "instrument": "strings"},
    "薰衣草":   {"valence_adj":  0.15, "arousal": 0.15, "effect": "float",     "color": "#B57EDC", "instrument": "flute"},
    "丁香":     {"valence_adj":  0.12, "arousal": 0.15, "effect": "float",     "color": "#C8A2C8", "instrument": "flute"},
    "树":       {"valence_adj":  0.05, "arousal": 0.20, "effect": "leaves",    "color": "#228B22", "instrument": "guitar"},
    "大树":     {"valence_adj":  0.08, "arousal": 0.22, "effect": "leaves",    "color": "#1A7A1A", "instrument": "guitar"},
    "古树":     {"valence_adj":  0.00, "arousal": 0.18, "effect": "leaves",    "color": "#3A5A2A", "instrument": "strings"},
    "柳树":     {"valence_adj":  0.05, "arousal": 0.18, "effect": "breeze",    "color": "#6B8E23", "instrument": "flute"},
    "松树":     {"valence_adj":  0.05, "arousal": 0.20, "effect": "wind",      "color": "#2E5A2E", "instrument": "strings"},
    "竹":       {"valence_adj":  0.10, "arousal": 0.20, "effect": "breeze",    "color": "#3CB371", "instrument": "flute"},
    "竹林":     {"valence_adj":  0.10, "arousal": 0.22, "effect": "breeze",    "color": "#2E8B57", "instrument": "flute"},
    "森林":     {"valence_adj":  0.10, "arousal": 0.25, "effect": "leaves",    "color": "#006400", "instrument": "guitar"},
    "树林":     {"valence_adj":  0.08, "arousal": 0.22, "effect": "leaves",    "color": "#1A6A1A", "instrument": "guitar"},
    "草":       {"valence_adj":  0.10, "arousal": 0.20, "effect": "breeze",    "color": "#7CFC00", "instrument": "flute"},
    "青草":     {"valence_adj":  0.12, "arousal": 0.22, "effect": "breeze",    "color": "#68D838", "instrument": "flute"},
    "落叶":     {"valence_adj": -0.10, "arousal": 0.20, "effect": "leaves",    "color": "#D2691E", "instrument": "guitar"},
    "枯叶":     {"valence_adj": -0.12, "arousal": 0.18, "effect": "leaves",    "color": "#A0522D", "instrument": "guitar"},
    "绿叶":     {"valence_adj":  0.15, "arousal": 0.22, "effect": "leaves",    "color": "#32CD32", "instrument": "guitar"},
    "叶子":     {"valence_adj":  0.05, "arousal": 0.18, "effect": "leaves",    "color": "#6AAF28", "instrument": "guitar"},
    "藤蔓":     {"valence_adj":  0.05, "arousal": 0.15, "effect": "float",     "color": "#4A8A2A", "instrument": "guitar"},
    "苔藓":     {"valence_adj":  0.03, "arousal": 0.10, "effect": "float",     "color": "#5A8A3A", "instrument": "piano"},
    "种子":     {"valence_adj":  0.10, "arousal": 0.15, "effect": "float",     "color": "#8B6914", "instrument": "celesta"},
    "果实":     {"valence_adj":  0.15, "arousal": 0.25, "effect": "sparkle",   "color": "#FF6347", "instrument": "bells"},

    # ==================== 火/光/暗/影（25+）====================
    "火":       {"valence_adj": -0.05, "arousal": 0.85, "effect": "fire",      "color": "#FF4500", "instrument": "drums"},
    "火焰":     {"valence_adj": -0.05, "arousal": 0.90, "effect": "fire",      "color": "#FF4500", "instrument": "drums"},
    "篝火":     {"valence_adj":  0.15, "arousal": 0.45, "effect": "fire",      "color": "#FF6600", "instrument": "guitar"},
    "烈火":     {"valence_adj": -0.10, "arousal": 0.95, "effect": "fire",      "color": "#FF2200", "instrument": "drums"},
    "火花":     {"valence_adj":  0.10, "arousal": 0.60, "effect": "sparkle",   "color": "#FFA500", "instrument": "celesta"},
    "烟花":     {"valence_adj":  0.30, "arousal": 0.85, "effect": "firework",  "color": "#FF69B4", "instrument": "bells"},
    "焰火":     {"valence_adj":  0.28, "arousal": 0.80, "effect": "firework",  "color": "#FF6EB4", "instrument": "bells"},
    "烛光":     {"valence_adj":  0.05, "arousal": 0.15, "effect": "candle",    "color": "#FFD700", "instrument": "piano"},
    "灯":       {"valence_adj":  0.05, "arousal": 0.20, "effect": "glow",      "color": "#FAFAD2", "instrument": "piano"},
    "灯火":     {"valence_adj":  0.08, "arousal": 0.25, "effect": "glow",      "color": "#FFE4B5", "instrument": "piano"},
    "灯光":     {"valence_adj":  0.05, "arousal": 0.22, "effect": "glow",      "color": "#FFFACD", "instrument": "piano"},
    "路灯":     {"valence_adj":  0.00, "arousal": 0.18, "effect": "glow",      "color": "#FFE8A0", "instrument": "piano"},
    "霓虹":     {"valence_adj":  0.10, "arousal": 0.55, "effect": "sparkle",   "color": "#FF00FF", "instrument": "synth_pad"},
    "光":       {"valence_adj":  0.15, "arousal": 0.40, "effect": "glow",      "color": "#FFFACD", "instrument": "bells"},
    "光芒":     {"valence_adj":  0.20, "arousal": 0.60, "effect": "burst",     "color": "#FFD700", "instrument": "bells"},
    "光线":     {"valence_adj":  0.12, "arousal": 0.35, "effect": "sunlight",  "color": "#FFE8A0", "instrument": "bells"},
    "光影":     {"valence_adj":  0.05, "arousal": 0.25, "effect": "glow",      "color": "#C8C8A0", "instrument": "piano"},
    "曙光":     {"valence_adj":  0.25, "arousal": 0.50, "effect": "sunrise",   "color": "#FF8C00", "instrument": "strings"},
    "暮光":     {"valence_adj":  0.00, "arousal": 0.25, "effect": "sunset",    "color": "#9370DB", "instrument": "synth_pad"},
    "极光":     {"valence_adj":  0.20, "arousal": 0.40, "effect": "aurora",    "color": "#00FF88", "instrument": "synth_pad"},
    "黑暗":     {"valence_adj": -0.20, "arousal": 0.40, "effect": "darkness",  "color": "#0D0D1A", "instrument": "synth_pad"},
    "黑夜":     {"valence_adj": -0.10, "arousal": 0.25, "effect": "darkness",  "color": "#0A0A20", "instrument": "synth_pad"},
    "阴影":     {"valence_adj": -0.10, "arousal": 0.30, "effect": "darkness",  "color": "#2A2A3A", "instrument": "synth_pad"},
    "影子":     {"valence_adj": -0.05, "arousal": 0.25, "effect": "darkness",  "color": "#3A3A4A", "instrument": "piano"},
    "烟":       {"valence_adj": -0.05, "arousal": 0.25, "effect": "smoke",     "color": "#888888", "instrument": "synth_pad"},
    "炊烟":     {"valence_adj":  0.10, "arousal": 0.15, "effect": "smoke",     "color": "#A0A0A0", "instrument": "flute"},
    "烟雾":     {"valence_adj": -0.05, "arousal": 0.20, "effect": "smoke",     "color": "#808080", "instrument": "synth_pad"},

    # ==================== 季节与时间（20+）====================
    "春":       {"valence_adj":  0.20, "arousal": 0.40, "effect": "petals",    "color": "#98FB98", "instrument": "flute"},
    "春天":     {"valence_adj":  0.20, "arousal": 0.40, "effect": "petals",    "color": "#98FB98", "instrument": "flute"},
    "春日":     {"valence_adj":  0.22, "arousal": 0.42, "effect": "petals",    "color": "#90F890", "instrument": "flute"},
    "初春":     {"valence_adj":  0.18, "arousal": 0.35, "effect": "breeze",    "color": "#A8E8A8", "instrument": "flute"},
    "夏":       {"valence_adj":  0.10, "arousal": 0.60, "effect": "sunlight",  "color": "#FFD700", "instrument": "guitar"},
    "夏天":     {"valence_adj":  0.10, "arousal": 0.60, "effect": "sunlight",  "color": "#FFD700", "instrument": "guitar"},
    "盛夏":     {"valence_adj":  0.08, "arousal": 0.70, "effect": "sunlight",  "color": "#FF8C00", "instrument": "guitar"},
    "秋":       {"valence_adj": -0.05, "arousal": 0.30, "effect": "leaves",    "color": "#DAA520", "instrument": "piano"},
    "秋天":     {"valence_adj": -0.05, "arousal": 0.30, "effect": "leaves",    "color": "#DAA520", "instrument": "piano"},
    "深秋":     {"valence_adj": -0.10, "arousal": 0.28, "effect": "leaves",    "color": "#B8860B", "instrument": "piano"},
    "金秋":     {"valence_adj":  0.10, "arousal": 0.35, "effect": "leaves",    "color": "#FFD700", "instrument": "guitar"},
    "冬":       {"valence_adj": -0.10, "arousal": 0.20, "effect": "snow",      "color": "#B0C4DE", "instrument": "celesta"},
    "冬天":     {"valence_adj": -0.10, "arousal": 0.20, "effect": "snow",      "color": "#B0C4DE", "instrument": "celesta"},
    "寒冬":     {"valence_adj": -0.15, "arousal": 0.25, "effect": "snow",      "color": "#8898B0", "instrument": "celesta"},
    "夜":       {"valence_adj": -0.05, "arousal": 0.20, "effect": "stars",     "color": "#191970", "instrument": "piano"},
    "夜晚":     {"valence_adj": -0.05, "arousal": 0.20, "effect": "stars",     "color": "#191970", "instrument": "piano"},
    "深夜":     {"valence_adj": -0.10, "arousal": 0.15, "effect": "stars",     "color": "#0D0D2B", "instrument": "synth_pad"},
    "午夜":     {"valence_adj": -0.10, "arousal": 0.18, "effect": "stars",     "color": "#0B0B28", "instrument": "synth_pad"},
    "凌晨":     {"valence_adj": -0.05, "arousal": 0.20, "effect": "moonlight", "color": "#1A1A40", "instrument": "piano"},
    "黎明":     {"valence_adj":  0.15, "arousal": 0.40, "effect": "sunrise",   "color": "#FF8C69", "instrument": "strings"},
    "拂晓":     {"valence_adj":  0.12, "arousal": 0.35, "effect": "sunrise",   "color": "#FF9980", "instrument": "flute"},
    "清晨":     {"valence_adj":  0.15, "arousal": 0.35, "effect": "sunlight",  "color": "#FFE4B5", "instrument": "flute"},
    "黄昏":     {"valence_adj": -0.05, "arousal": 0.25, "effect": "sunset",    "color": "#CD853F", "instrument": "guitar"},
    "傍晚":     {"valence_adj": -0.03, "arousal": 0.22, "effect": "sunset",    "color": "#D89050", "instrument": "guitar"},
    "正午":     {"valence_adj":  0.10, "arousal": 0.50, "effect": "sunlight",  "color": "#FFCC00", "instrument": "guitar"},

    # ==================== 动物（20+）====================
    "鸟":       {"valence_adj":  0.10, "arousal": 0.40, "effect": "float",     "color": "#87CEEB", "instrument": "flute"},
    "小鸟":     {"valence_adj":  0.15, "arousal": 0.35, "effect": "float",     "color": "#90D0F0", "instrument": "flute"},
    "飞鸟":     {"valence_adj":  0.12, "arousal": 0.50, "effect": "float",     "color": "#80C0E0", "instrument": "flute"},
    "鹰":       {"valence_adj":  0.05, "arousal": 0.60, "effect": "wind",      "color": "#5A4A3A", "instrument": "strings"},
    "燕子":     {"valence_adj":  0.15, "arousal": 0.40, "effect": "float",     "color": "#2A2A3A", "instrument": "flute"},
    "蝴蝶":     {"valence_adj":  0.20, "arousal": 0.30, "effect": "petals",    "color": "#DA70D6", "instrument": "bells"},
    "蜻蜓":     {"valence_adj":  0.15, "arousal": 0.25, "effect": "float",     "color": "#66CDAA", "instrument": "celesta"},
    "萤火虫":   {"valence_adj":  0.20, "arousal": 0.20, "effect": "firefly",   "color": "#CCFF00", "instrument": "celesta"},
    "蝉":       {"valence_adj":  0.00, "arousal": 0.35, "effect": "float",     "color": "#8B8B00", "instrument": "synth_pad"},
    "鱼":       {"valence_adj":  0.10, "arousal": 0.20, "effect": "ripple",    "color": "#4682B4", "instrument": "piano"},
    "金鱼":     {"valence_adj":  0.15, "arousal": 0.18, "effect": "ripple",    "color": "#FF6347", "instrument": "celesta"},
    "鲸":       {"valence_adj":  0.10, "arousal": 0.40, "effect": "wave",      "color": "#2A5A8A", "instrument": "synth_pad"},
    "鲸鱼":     {"valence_adj":  0.10, "arousal": 0.40, "effect": "wave",      "color": "#2A5A8A", "instrument": "synth_pad"},
    "猫":       {"valence_adj":  0.15, "arousal": 0.20, "effect": "float",     "color": "#DEB887", "instrument": "piano"},
    "小猫":     {"valence_adj":  0.20, "arousal": 0.22, "effect": "float",     "color": "#E0C8A0", "instrument": "celesta"},
    "狗":       {"valence_adj":  0.15, "arousal": 0.40, "effect": "sparkle",   "color": "#C8A060", "instrument": "guitar"},
    "马":       {"valence_adj":  0.10, "arousal": 0.55, "effect": "wind",      "color": "#8B4513", "instrument": "strings"},
    "白鸽":     {"valence_adj":  0.20, "arousal": 0.30, "effect": "float",     "color": "#F0F0F0", "instrument": "flute"},
    "鹤":       {"valence_adj":  0.10, "arousal": 0.25, "effect": "float",     "color": "#E8E8E8", "instrument": "flute"},
    "蛙":       {"valence_adj":  0.05, "arousal": 0.25, "effect": "ripple",    "color": "#3CB371", "instrument": "celesta"},
    "虫":       {"valence_adj":  0.00, "arousal": 0.15, "effect": "float",     "color": "#808000", "instrument": "celesta"},

    # ==================== 地点/建筑/空间（20+）====================
    "远方":     {"valence_adj":  0.00, "arousal": 0.30, "effect": "drift",     "color": "#B0C4DE", "instrument": "synth_pad"},
    "故乡":     {"valence_adj":  0.05, "arousal": 0.25, "effect": "glow",      "color": "#DAA520", "instrument": "guitar"},
    "家":       {"valence_adj":  0.15, "arousal": 0.20, "effect": "glow",      "color": "#FFE4B5", "instrument": "piano"},
    "家乡":     {"valence_adj":  0.08, "arousal": 0.25, "effect": "glow",      "color": "#D4A520", "instrument": "guitar"},
    "路":       {"valence_adj":  0.00, "arousal": 0.30, "effect": "drift",     "color": "#808080", "instrument": "piano"},
    "小路":     {"valence_adj":  0.05, "arousal": 0.22, "effect": "drift",     "color": "#909060", "instrument": "guitar"},
    "长路":     {"valence_adj": -0.03, "arousal": 0.32, "effect": "drift",     "color": "#787878", "instrument": "strings"},
    "桥":       {"valence_adj":  0.05, "arousal": 0.22, "effect": "float",     "color": "#A0A0A0", "instrument": "piano"},
    "窗":       {"valence_adj":  0.00, "arousal": 0.15, "effect": "glow",      "color": "#FAFAD2", "instrument": "piano"},
    "窗外":     {"valence_adj": -0.03, "arousal": 0.18, "effect": "glow",      "color": "#E8E8C0", "instrument": "piano"},
    "门":       {"valence_adj":  0.00, "arousal": 0.20, "effect": "float",     "color": "#8B7355", "instrument": "piano"},
    "城市":     {"valence_adj":  0.05, "arousal": 0.50, "effect": "sparkle",   "color": "#FFD700", "instrument": "synth_pad"},
    "街":       {"valence_adj":  0.00, "arousal": 0.40, "effect": "drift",     "color": "#A0A0A0", "instrument": "piano"},
    "街道":     {"valence_adj":  0.00, "arousal": 0.40, "effect": "drift",     "color": "#A0A0A0", "instrument": "piano"},
    "古镇":     {"valence_adj":  0.08, "arousal": 0.20, "effect": "glow",      "color": "#8B7355", "instrument": "guitar"},
    "村庄":     {"valence_adj":  0.10, "arousal": 0.18, "effect": "smoke",     "color": "#A09060", "instrument": "guitar"},
    "花园":     {"valence_adj":  0.20, "arousal": 0.30, "effect": "petals",    "color": "#90EE90", "instrument": "flute"},
    "庭院":     {"valence_adj":  0.12, "arousal": 0.18, "effect": "float",     "color": "#8FAF6F", "instrument": "guitar"},
    "寺庙":     {"valence_adj":  0.05, "arousal": 0.15, "effect": "smoke",     "color": "#8B7355", "instrument": "bells"},
    "教堂":     {"valence_adj":  0.08, "arousal": 0.20, "effect": "glow",      "color": "#B8A888", "instrument": "bells"},
    "废墟":     {"valence_adj": -0.15, "arousal": 0.25, "effect": "dust",      "color": "#6A6A5A", "instrument": "strings"},

    # ==================== 人体/感知/抽象物（15+）====================
    "泪":       {"valence_adj": -0.15, "arousal": 0.40, "effect": "light_rain","color": "#6A8AB0", "instrument": "piano"},
    "眼泪":     {"valence_adj": -0.15, "arousal": 0.40, "effect": "light_rain","color": "#6A8AB0", "instrument": "piano"},
    "笑容":     {"valence_adj":  0.25, "arousal": 0.45, "effect": "sparkle",   "color": "#FFD700", "instrument": "bells"},
    "微笑":     {"valence_adj":  0.22, "arousal": 0.35, "effect": "sparkle",   "color": "#FFD700", "instrument": "bells"},
    "呼吸":     {"valence_adj":  0.00, "arousal": 0.15, "effect": "breeze",    "color": "#C8D8E8", "instrument": "synth_pad"},
    "心跳":     {"valence_adj":  0.05, "arousal": 0.60, "effect": "glow",      "color": "#FF4444", "instrument": "drums"},
    "梦":       {"valence_adj":  0.05, "arousal": 0.15, "effect": "aurora",    "color": "#9370DB", "instrument": "synth_pad"},
    "梦境":     {"valence_adj":  0.08, "arousal": 0.18, "effect": "aurora",    "color": "#8A60D0", "instrument": "synth_pad"},
    "回忆":     {"valence_adj": -0.03, "arousal": 0.20, "effect": "fog",       "color": "#B8A8C8", "instrument": "piano"},
    "记忆":     {"valence_adj": -0.03, "arousal": 0.20, "effect": "fog",       "color": "#B0A0C0", "instrument": "piano"},
    "时光":     {"valence_adj":  0.00, "arousal": 0.20, "effect": "drift",     "color": "#C8B8A0", "instrument": "piano"},
    "岁月":     {"valence_adj": -0.03, "arousal": 0.18, "effect": "drift",     "color": "#B8A888", "instrument": "piano"},
    "影":       {"valence_adj": -0.05, "arousal": 0.22, "effect": "darkness",  "color": "#3A3A4A", "instrument": "piano"},
    "声音":     {"valence_adj":  0.00, "arousal": 0.30, "effect": "ripple",    "color": "#A0B8D0", "instrument": "piano"},
    "歌":       {"valence_adj":  0.10, "arousal": 0.35, "effect": "float",     "color": "#DDA0DD", "instrument": "bells"},
    "歌声":     {"valence_adj":  0.12, "arousal": 0.38, "effect": "float",     "color": "#D890D8", "instrument": "bells"},
    "琴声":     {"valence_adj":  0.10, "arousal": 0.25, "effect": "ripple",    "color": "#C8A860", "instrument": "piano"},
    "钟声":     {"valence_adj":  0.05, "arousal": 0.30, "effect": "ripple",    "color": "#B0A060", "instrument": "bells"},
}

# ==================== 情绪关键词修正表（80+）====================
EMOTION_KEYWORDS = {
    # ==================== 积极 ====================
    # 强积极（狂喜、激动）
    "幸福":  0.20, "狂喜":  0.25, "兴奋":  0.20, "激动":  0.18, "欣喜":  0.20,
    "陶醉":  0.18, "快乐":  0.15, "开心":  0.15, "高兴":  0.15, "喜悦":  0.15,
    "欢笑":  0.15, "欢乐":  0.15, "欢喜":  0.15, "愉快":  0.12, "惊喜":  0.15,
    "狂欢":  0.22, "雀跃":  0.20, "振奋":  0.18, "欢腾":  0.20, "灿烂":  0.16,
    "璀璨":  0.15, "热烈":  0.15, "酣畅":  0.15, "畅快":  0.15, "尽兴":  0.16,

    # 中积极（温暖、希望、向往）
    "温暖":  0.12, "温柔":  0.10, "温馨":  0.12, "甜蜜":  0.15, "美好":  0.12,
    "希望":  0.12, "期待":  0.10, "憧憬":  0.10, "向往":  0.08, "自由":  0.10,
    "勇敢":  0.10, "坚强":  0.08, "安心":  0.10, "安宁":  0.08, "满足":  0.10,
    "感恩":  0.10, "珍惜":  0.08, "祝福":  0.12, "治愈":  0.12, "惬意":  0.12,
    "舒畅":  0.12, "悠然":  0.10, "从容":  0.08, "踏实":  0.08, "欣慰":  0.10,
    "暖心":  0.12, "浪漫":  0.12, "幸运":  0.12, "圆满":  0.12, "重逢":  0.12,
    "团聚":  0.12, "收获":  0.10, "成长":  0.08, "笃定":  0.08, "明媚":  0.12,
    "灿然":  0.12, "甜":    0.10, "暖":    0.08,

    # 弱积极（陪伴、喜欢、平静）
    "笑":    0.10, "爱":    0.15, "拥抱":  0.12, "亲吻":  0.12, "陪伴":  0.10,
    "喜欢":  0.10, "热爱":  0.12, "眷恋":  0.08, "心动":  0.10, "平静":  0.05,
    "宁静":  0.05, "淡然":  0.03, "释然":  0.08, "轻松":  0.08, "微笑":  0.10,
    "守候":  0.06, "相伴":  0.10, "心安":  0.10, "释怀":  0.08, "期盼":  0.08,
    "安详":  0.06, "安然":  0.06, "悠扬":  0.05, "静谧":  0.04, "恬静":  0.05,
    "祥和":  0.06, "惦念":  0.04,

    # ==================== 消极 ====================
    # 弱消极（思念、惆怅、迷茫）
    "思念": -0.05, "想念": -0.05, "牵挂": -0.05, "惆怅": -0.08, "感伤": -0.08,
    "沉默": -0.05, "无奈": -0.08, "叹息": -0.08, "遗憾": -0.10, "迷茫": -0.10,
    "彷徨": -0.10, "犹豫": -0.05, "疲惫": -0.10, "倦怠": -0.08, "怅然": -0.08,
    "黯然": -0.10, "空虚": -0.10, "麻木": -0.10, "恍惚": -0.08, "茫然": -0.10,
    "厌倦": -0.10, "烦躁": -0.10, "心烦": -0.10, "委屈": -0.12, "不安": -0.10,
    "担忧": -0.10, "忐忑": -0.10, "愧疚": -0.10, "后悔": -0.10, "踌躇": -0.06,
    "想家": -0.06, "失神": -0.06, "怀念": -0.04,

    # 中消极（悲伤、孤独、离别）
    "悲伤": -0.15, "难过": -0.15, "伤心": -0.15, "心痛": -0.15, "哭":   -0.15,
    "流泪": -0.12, "孤独": -0.15, "寂寞": -0.15, "落寞": -0.12, "凄凉": -0.15,
    "失落": -0.15, "离别": -0.10, "分离": -0.10, "告别": -0.08, "冷":   -0.10,
    "寒冷": -0.10, "冰冷": -0.12, "荒凉": -0.12, "悲哀": -0.15, "悲凉": -0.15,
    "哀伤": -0.15, "哀愁": -0.14, "忧伤": -0.15, "忧郁": -0.15, "忧愁": -0.14,
    "沮丧": -0.15, "颓废": -0.15, "消沉": -0.15, "孤单": -0.15, "孤寂": -0.15,
    "苍凉": -0.14, "萧瑟": -0.12, "漂泊": -0.10, "流浪": -0.10, "别离": -0.10,
    "失去": -0.14, "错过": -0.12, "遗忘": -0.10, "冷清": -0.12, "凄苦": -0.16,
    "心酸": -0.14, "哽咽": -0.14, "酸楚": -0.14,

    # 强消极（绝望、恐惧、愤怒）
    "绝望": -0.25, "痛苦": -0.20, "崩溃": -0.22, "窒息": -0.20, "恐惧": -0.20,
    "愤怒": -0.15, "暴怒": -0.20, "仇恨": -0.20, "嫉妒": -0.10, "焦虑": -0.12,
    "压抑": -0.15, "煎熬": -0.18, "挣扎": -0.12, "沉沦": -0.18, "悲恸": -0.22,
    "心碎": -0.20, "撕心裂肺": -0.24, "万念俱灰": -0.25, "生无可恋": -0.25,
    "惊恐": -0.20, "战栗": -0.18, "恐慌": -0.20, "狂怒": -0.20, "怨恨": -0.18,
    "痛恨": -0.20, "沉痛": -0.18, "悲愤": -0.18, "凄厉": -0.18, "哀嚎": -0.20,
    "崩塌": -0.16, "心如死灰": -0.24,
}
